-- base_node_test.TB_CHAT_ROOM definition

CREATE TABLE `TB_CHAT_ROOM` (
  `CHAT_ROOM_ID` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `NAME` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `USER_COUNT` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`CHAT_ROOM_ID`),
  KEY `IDX_CHAT_ROOM__NAME` (`NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- base_node_test.TB_CRAWLING definition

CREATE TABLE `TB_CRAWLING` (
  `URL` varchar(300) COLLATE utf8mb4_unicode_ci NOT NULL,
  `CONTENT` longtext COLLATE utf8mb4_unicode_ci,
  `REG_DT` datetime DEFAULT NULL,
  `CHG_DT` datetime DEFAULT NULL,
  PRIMARY KEY (`URL`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- base_node_test.TB_EMAIL_LOG definition

CREATE TABLE `TB_EMAIL_LOG` (
  `EMAIL_LOG_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CONTENT` longtext COLLATE utf8mb4_unicode_ci,
  `REG_DT` datetime DEFAULT NULL,
  `MAIL_FROM` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `SEND_TYPE` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `TITLE` varchar(1000) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `MAIL_TO` longtext COLLATE utf8mb4_unicode_ci,
  PRIMARY KEY (`EMAIL_LOG_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- base_node_test.TB_ERROR_LOG definition

CREATE TABLE `TB_ERROR_LOG` (
  `ERROR_LOG_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `REG_DT` datetime DEFAULT NULL,
  `ERROR_DETAIL` longtext COLLATE utf8mb4_unicode_ci,
  `ERROR_TITLE` longtext COLLATE utf8mb4_unicode_ci,
  PRIMARY KEY (`ERROR_LOG_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- base_node_test.TB_PRODUCTS definition

CREATE TABLE `TB_PRODUCTS` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT '',
  `PRICE` int(11) NOT NULL,
  `DESCRIPTION` longtext COLLATE utf8mb4_unicode_ci,
  `REG_DT` datetime DEFAULT NULL,
  `CHG_DT` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `t_b__p_r_o_d_u_c_t_s_name` (`NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- base_node_test.TB_TAG definition

CREATE TABLE `TB_TAG` (
  `TAG_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `TAG_NAME` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`TAG_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- base_node_test.TB_USER_DEACTI_NOTIF definition

CREATE TABLE `TB_USER_DEACTI_NOTIF` (
  `NOTIF_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `REG_DT` datetime DEFAULT NULL,
  `LOGIN_DT` datetime DEFAULT NULL,
  `REASON_ID` bigint(20) DEFAULT NULL,
  `USER_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`NOTIF_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- base_node_test.TB_USER_DESTROY definition

CREATE TABLE `TB_USER_DESTROY` (
  `USER_ID` bigint(20) NOT NULL,
  `REG_DT` datetime DEFAULT NULL,
  `DESTROY_TYPE` char(1) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- base_node_test.TB_USER_LOGIN_LOG definition

CREATE TABLE `TB_USER_LOGIN_LOG` (
  `LOGIN_LOG_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `REG_DT` datetime DEFAULT NULL,
  `REG_IP` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `LOGIN_LOG_TYPE` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `LOGIN_ID` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `USER_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`LOGIN_LOG_ID`),
  KEY `IDX_USER_LOGIN_LOG__LOGIN_LOG_TYPE` (`LOGIN_LOG_TYPE`),
  KEY `IDX_USER_LOGIN_LOG__REG_DT` (`REG_DT`),
  KEY `IDX_USER_LOGIN_LOG__REG_IP` (`REG_IP`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- base_node_test.TB_USER_ROLE definition

CREATE TABLE `TB_USER_ROLE` (
  `ROLE_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `REG_DT` datetime DEFAULT NULL,
  `REG_IP` varchar(15) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CHG_DT` datetime DEFAULT NULL,
  `CHG_IP` varchar(15) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ROLE_NAME` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ROLE_GROUP` varchar(300) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`ROLE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- base_node_test.sessions definition

CREATE TABLE `sessions` (
  `session_id` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `expires` int(11) unsigned NOT NULL,
  `data` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  PRIMARY KEY (`session_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- base_node_test.TB_TAG_RELATION definition

CREATE TABLE `TB_TAG_RELATION` (
  `OBJECT_ID` bigint(20) NOT NULL,
  `TAG_ID` bigint(20) NOT NULL,
  `TAG_TYPE` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`OBJECT_ID`,`TAG_ID`,`TAG_TYPE`),
  KEY `FK_TAG_RELATION_TO_TAG` (`TAG_ID`),
  CONSTRAINT `FK_TAG_RELATION_TO_TAG` FOREIGN KEY (`TAG_ID`) REFERENCES `TB_TAG` (`TAG_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- base_node_test.TB_USER definition

CREATE TABLE `TB_USER` (
  `USER_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `ADDRESS1` varchar(400) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ADDRESS2` varchar(400) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `BIRTHDAY` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `REG_DT` datetime DEFAULT NULL,
  `REG_IP` varchar(15) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `EMAIL` varchar(300) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `FACEBOOK_CODE` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `GITHUB_CODE` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `GOOGLE_CODE` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `USER_IMAGE` varchar(300) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `KAKAO_CODE` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `LOGIN_DT` datetime DEFAULT NULL,
  `LOGIN_ID` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CHG_DT` datetime DEFAULT NULL,
  `USER_NAME` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `NAVER_CODE` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `USER_NICK` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `PASSWD` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `PASSWD_CHG_DT` datetime DEFAULT NULL,
  `PASSWD_FAIL_CNT` int(11) DEFAULT NULL,
  `PHONE` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `POST_CODE` varchar(12) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `USER_STATUS` char(1) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ROLE_ID` bigint(20) DEFAULT 3,
  PRIMARY KEY (`USER_ID`),
  UNIQUE KEY `UQ_USER__LOGIN_ID` (`LOGIN_ID`),
  UNIQUE KEY `UQ_USER__NAVER_CODE` (`NAVER_CODE`),
  UNIQUE KEY `UQ_USER__FACEBOOK_CODE` (`FACEBOOK_CODE`),
  UNIQUE KEY `UQ_USER__KAKAO_CODE` (`KAKAO_CODE`),
  UNIQUE KEY `UQ_USER__GOOGLE_CODE` (`GOOGLE_CODE`),
  UNIQUE KEY `UQ_USER__GITHUB_CODE` (`GITHUB_CODE`),
  UNIQUE KEY `UQ_USER__EMAIL` (`EMAIL`),
  UNIQUE KEY `UQ_USER__USER_NICK` (`USER_NICK`),
  KEY `IDX_USER__PHONE` (`PHONE`),
  KEY `IDX_USER__USER_NAME` (`USER_NAME`),
  KEY `IDX_USER__USER_STATUS` (`USER_STATUS`),
  KEY `ROLE_ID` (`ROLE_ID`),
  CONSTRAINT `tb_user_ibfk_1` FOREIGN KEY (`ROLE_ID`) REFERENCES `TB_USER_ROLE` (`ROLE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=27 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- base_node_test.TB_USER_DEACTIVATE definition

CREATE TABLE `TB_USER_DEACTIVATE` (
  `USER_ID` bigint(20) NOT NULL,
  `ADDRESS1` varchar(400) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ADDRESS2` varchar(400) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `BIRTHDAY` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `REG_DT` datetime DEFAULT NULL,
  `REG_IP` varchar(15) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `EMAIL` varchar(300) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `FACEBOOK_CODE` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `GITHUB_CODE` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `GOOGLE_CODE` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `USER_IMAGE` varchar(300) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `KAKAO_CODE` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `LOGIN_DT` datetime DEFAULT NULL,
  `LOGIN_ID` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CHG_DT` datetime DEFAULT NULL,
  `USER_NAME` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `NAVER_CODE` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `USER_NICK` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `PASSWD` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `PASSWD_CHG_DT` datetime DEFAULT NULL,
  `PASSWD_FAIL_CNT` int(11) DEFAULT NULL,
  `PHONE` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `POST_CODE` varchar(12) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `USER_STATUS` char(1) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `DEACTIVATE_DT` datetime DEFAULT NULL,
  `ROLE_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`USER_ID`),
  KEY `IDX_USER_DEACTIVATE__LOGIN_ID` (`LOGIN_ID`),
  KEY `ROLE_ID` (`ROLE_ID`),
  CONSTRAINT `tb_user_deactivate_ibfk_1` FOREIGN KEY (`ROLE_ID`) REFERENCES `TB_USER_ROLE` (`ROLE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- base_node_test.TB_USER_RESET_PASSWORD_TOKEN definition

CREATE TABLE `TB_USER_RESET_PASSWORD_TOKEN` (
  `USER_RESET_PASSWORD_TOKEN_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `REG_DT` datetime DEFAULT NULL,
  `REG_IP` varchar(15) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `TOKEN` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `TARGET_USER_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`USER_RESET_PASSWORD_TOKEN_ID`),
  UNIQUE KEY `UQ_USER_RESET_PASSWORD_TOKEN__TOKEN` (`TOKEN`),
  KEY `TARGET_USER_ID` (`TARGET_USER_ID`),
  CONSTRAINT `tb_user_reset_password_token_ibfk_1` FOREIGN KEY (`TARGET_USER_ID`) REFERENCES `TB_USER` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- base_node_test.TB_USER_WITHDRAWAL definition

CREATE TABLE `TB_USER_WITHDRAWAL` (
  `USER_ID` bigint(20) NOT NULL,
  `ADDRESS1` varchar(400) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ADDRESS2` varchar(400) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `BIRTHDAY` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `REG_DT` datetime DEFAULT NULL,
  `REG_IP` varchar(15) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `EMAIL` varchar(300) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `FACEBOOK_CODE` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `GITHUB_CODE` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `GOOGLE_CODE` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `USER_IMAGE` varchar(300) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `KAKAO_CODE` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `LOGIN_DT` datetime DEFAULT NULL,
  `LOGIN_ID` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CHG_DT` datetime DEFAULT NULL,
  `USER_NAME` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `NAVER_CODE` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `USER_NICK` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `PASSWD` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `PASSWD_CHG_DT` datetime DEFAULT NULL,
  `PASSWD_FAIL_CNT` int(11) DEFAULT NULL,
  `PHONE` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `POST_CODE` varchar(12) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `USER_STATUS` char(1) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `WITHDRAWAL_DT` datetime DEFAULT NULL,
  `WITHDRAWAL_REASON` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `WITHDRAWAL_TYPE` char(1) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ROLE_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`USER_ID`),
  KEY `IDX_TB_USER_WITHDRAWAL__LOGIN_ID` (`LOGIN_ID`),
  KEY `ROLE_ID` (`ROLE_ID`),
  CONSTRAINT `tb_user_withdrawal_ibfk_1` FOREIGN KEY (`ROLE_ID`) REFERENCES `TB_USER_ROLE` (`ROLE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- base_node_test.TB_ATTACHED_FILE definition

CREATE TABLE `TB_ATTACHED_FILE` (
  `ATTACHED_FILE_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `REG_DT` datetime DEFAULT NULL,
  `REG_IP` varchar(15) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `FILE_NAME` varchar(300) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `FILE_SIZE` bigint(20) DEFAULT NULL,
  `FILE_URL` varchar(300) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `FILE_UUID` char(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `REG_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ATTACHED_FILE_ID`),
  UNIQUE KEY `UQ_ATTACHED_FILE__FILE_UUID` (`FILE_UUID`),
  KEY `REG_ID` (`REG_ID`),
  CONSTRAINT `tb_attached_file_ibfk_1` FOREIGN KEY (`REG_ID`) REFERENCES `TB_USER` (`USER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- base_node_test.TB_BOARD_CTGRY definition

CREATE TABLE `TB_BOARD_CTGRY` (
  `BOARD_CTGRY_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `REG_DT` datetime DEFAULT NULL,
  `REG_IP` varchar(15) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `MENU_UID` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CHG_DT` datetime DEFAULT NULL,
  `CHG_IP` varchar(15) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `NAME` varchar(300) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `STATUS` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `REG_ID` bigint(20) DEFAULT NULL,
  `CHG_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`BOARD_CTGRY_ID`),
  KEY `IDX_BOARD_CTGRY__MENU_UID` (`MENU_UID`),
  KEY `IDX_BOARD_CTGRY__STATUS` (`STATUS`),
  KEY `REG_ID` (`REG_ID`),
  KEY `CHG_ID` (`CHG_ID`),
  CONSTRAINT `tb_board_ctgry_ibfk_1` FOREIGN KEY (`REG_ID`) REFERENCES `TB_USER` (`USER_ID`),
  CONSTRAINT `tb_board_ctgry_ibfk_2` FOREIGN KEY (`CHG_ID`) REFERENCES `TB_USER` (`USER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- base_node_test.TB_CHAT_MESSAGE definition

CREATE TABLE `TB_CHAT_MESSAGE` (
  `CHAT_MESSAGE_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `MESSAGE` longtext COLLATE utf8mb4_unicode_ci,
  `MESSAGE_TYPE` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CHAT_ROOM_ID` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `SENDER` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`CHAT_MESSAGE_ID`),
  KEY `CHAT_ROOM_ID` (`CHAT_ROOM_ID`),
  KEY `SENDER` (`SENDER`),
  CONSTRAINT `tb_chat_message_ibfk_3` FOREIGN KEY (`CHAT_ROOM_ID`) REFERENCES `TB_CHAT_ROOM` (`CHAT_ROOM_ID`),
  CONSTRAINT `tb_chat_message_ibfk_4` FOREIGN KEY (`SENDER`) REFERENCES `TB_USER` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- base_node_test.TB_CHAT_ROOM_USER definition

CREATE TABLE `TB_CHAT_ROOM_USER` (
  `CHAT_ROOM_ID` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `USER_ID` bigint(20) NOT NULL,
  `SESSION_ID` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`CHAT_ROOM_ID`,`USER_ID`),
  KEY `IDX_CHAT_ROOM_USER__SESSION_ID` (`SESSION_ID`),
  KEY `FK_CHAT_ROOM_USER_TO_USER` (`USER_ID`),
  CONSTRAINT `FK_CHAT_ROOM_USER_TO_CHATROOM` FOREIGN KEY (`CHAT_ROOM_ID`) REFERENCES `TB_CHAT_ROOM` (`CHAT_ROOM_ID`),
  CONSTRAINT `FK_CHAT_ROOM_USER_TO_USER` FOREIGN KEY (`USER_ID`) REFERENCES `TB_USER` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- base_node_test.TB_COMMENT definition

CREATE TABLE `TB_COMMENT` (
  `COMMENT_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `COMMENT_CONTENT` longtext COLLATE utf8mb4_unicode_ci,
  `REG_DT` datetime DEFAULT NULL,
  `REG_IP` varchar(15) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `COMMENT_IMAGE` varchar(300) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `MENU_UID` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CHG_DT` datetime DEFAULT NULL,
  `CHG_IP` varchar(15) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `COMMENT_RATING` char(1) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `STATUS` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `TYPE_ID` bigint(20) DEFAULT NULL,
  `REG_ID` bigint(20) DEFAULT NULL,
  `CHG_ID` bigint(20) DEFAULT NULL,
  `PARENT_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`COMMENT_ID`),
  KEY `REG_ID` (`REG_ID`),
  KEY `CHG_ID` (`CHG_ID`),
  KEY `PARENT_ID` (`PARENT_ID`),
  CONSTRAINT `tb_comment_ibfk_4` FOREIGN KEY (`REG_ID`) REFERENCES `TB_USER` (`USER_ID`),
  CONSTRAINT `tb_comment_ibfk_5` FOREIGN KEY (`CHG_ID`) REFERENCES `TB_USER` (`USER_ID`),
  CONSTRAINT `tb_comment_ibfk_6` FOREIGN KEY (`PARENT_ID`) REFERENCES `TB_COMMENT` (`COMMENT_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=101 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- base_node_test.TB_POPUP definition

CREATE TABLE `TB_POPUP` (
  `POPUP_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `REG_DT` datetime DEFAULT NULL,
  `REG_IP` varchar(15) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `POPUP_DESKTOP_IMAGE` varchar(300) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `POPUP_ED_DATE` date DEFAULT NULL,
  `MENU_UID` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `POPUP_MOBILE_IMAGE` varchar(300) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CHG_DT` datetime DEFAULT NULL,
  `CHG_IP` varchar(15) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `NEW_WINDOW_YN` tinyint(1) DEFAULT NULL,
  `POPUP_POSITION` varchar(15) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `POPUP_TYPE` varchar(15) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `POPUP_ST_DATE` date DEFAULT NULL,
  `STATUS` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `POPUP_TITLE` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `POPUP_TXT` varchar(1000) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `POPUP_TXT_CONTENT` longtext COLLATE utf8mb4_unicode_ci,
  `POPUP_URL` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `REG_ID` bigint(20) DEFAULT NULL,
  `CHG_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`POPUP_ID`),
  KEY `IDX_POPUP__POPUP_ST_DATE` (`POPUP_ST_DATE`),
  KEY `IDX_POPUP__POPUP_ED_DATE` (`POPUP_ED_DATE`),
  KEY `IDX_POPUP__POPUP_STATUS` (`STATUS`),
  KEY `IDX_POPUP__MENU_UID` (`MENU_UID`),
  KEY `REG_ID` (`REG_ID`),
  KEY `CHG_ID` (`CHG_ID`),
  CONSTRAINT `tb_popup_ibfk_1` FOREIGN KEY (`REG_ID`) REFERENCES `TB_USER` (`USER_ID`),
  CONSTRAINT `tb_popup_ibfk_2` FOREIGN KEY (`CHG_ID`) REFERENCES `TB_USER` (`USER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- base_node_test.TB_SCHEDULE_JOB definition

CREATE TABLE `TB_SCHEDULE_JOB` (
  `SCHEDULE_JOB_ID` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `JOB_NAME` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CHG_DT` datetime DEFAULT NULL,
  `CHG_IP` varchar(15) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `RUN_YN` tinyint(1) DEFAULT NULL,
  `CHG_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`SCHEDULE_JOB_ID`),
  KEY `CHG_ID` (`CHG_ID`),
  CONSTRAINT `tb_schedule_job_ibfk_1` FOREIGN KEY (`CHG_ID`) REFERENCES `TB_USER` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- base_node_test.TB_SCHEDULE_JOB_LOG definition

CREATE TABLE `TB_SCHEDULE_JOB_LOG` (
  `SCHEDULE_LOG_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `ERROR_DETAIL` longtext COLLATE utf8mb4_unicode_ci,
  `ERROR_TITLE` longtext COLLATE utf8mb4_unicode_ci,
  `JOB_LOG_TYPE` varchar(5) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `JOB_NAME` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `LOG_DT` datetime DEFAULT NULL,
  `SCHEDULE_JOB_ID` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`SCHEDULE_LOG_ID`),
  KEY `SCHEDULE_JOB_ID` (`SCHEDULE_JOB_ID`),
  CONSTRAINT `tb_schedule_job_log_ibfk_1` FOREIGN KEY (`SCHEDULE_JOB_ID`) REFERENCES `TB_SCHEDULE_JOB` (`SCHEDULE_JOB_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- base_node_test.TB_SITE_CONFIG definition

CREATE TABLE `TB_SITE_CONFIG` (
  `SITE_CONFIG_ID` int(11) NOT NULL AUTO_INCREMENT,
  `REG_DT` datetime DEFAULT NULL,
  `REG_IP` varchar(15) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `DESIGN_TEMPLATE` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `EMAIL_YN` tinyint(1) DEFAULT NULL,
  `ERROR_NOTI_YN` tinyint(1) DEFAULT NULL,
  `FACEBOOK_APP_ID` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `FACEBOOK_APP_SECRET_CODE` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `GOOGLE_ANALYTICS_ID` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `GITHUB_CLIENT_ID` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `GITHUB_CLIENT_SECRET` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `GOOGLE_CLIENT_ID` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `GOOGLE_CLIENT_SECRET` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `GOOGLE_SITE_VERIFICATION` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `KAKAO_JAVASCRIPT_KEY` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `KAKAO_RESTAPI_KEY` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CHG_DT` datetime DEFAULT NULL,
  `CHG_IP` varchar(15) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `NAVER_CLIENT_ID` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `NAVER_CLIENT_SECRET` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `NAVER_SITE_VERIFICATION` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `NOTI_SLACK_CHANNEL_NAME` varchar(300) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `RECAPTCHA_V3_SCORE` double DEFAULT NULL,
  `RECAPTCHA_V2_CLIENT` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `RECAPTCHA_V2_SERVER` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `RECAPTCHA_V3_CLIENT` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `RECAPTCHA_V3_SERVER` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `REPRESENT_ADDRESS` varchar(300) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `REPRESENT_EMAIL` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `REPRESENT_FACEBOOK` varchar(300) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `REPRESENT_FAX` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `REPRESENT_INSTAGRAM` varchar(300) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `REPRESENT_KAKAO` varchar(300) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `REPRESENT_NAVER` varchar(300) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `REPRESENT_PHONE` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `REPRESENT_TWITTER` varchar(300) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `REPRESENT_YOUTUBE` varchar(300) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `SEO_SITE_COPYRIGHT` varchar(300) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `SEO_SITE_DESC` longtext COLLATE utf8mb4_unicode_ci,
  `SEO_SITE_KEYWORDS` varchar(300) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `SITE_NAME` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `SEO_SITE_SUBJECT` varchar(300) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `SLACK_BOT_OAUTH_TOKEN` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `SLEEP_USER_INSTANT_DESTROY_YN` tinyint(1) DEFAULT NULL,
  `REG_ID` bigint(20) DEFAULT NULL,
  `CHG_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`SITE_CONFIG_ID`),
  KEY `REG_ID` (`REG_ID`),
  KEY `CHG_ID` (`CHG_ID`),
  CONSTRAINT `tb_site_config_ibfk_1` FOREIGN KEY (`REG_ID`) REFERENCES `TB_USER` (`USER_ID`),
  CONSTRAINT `tb_site_config_ibfk_2` FOREIGN KEY (`CHG_ID`) REFERENCES `TB_USER` (`USER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- base_node_test.TB_TERM_CTGRY definition

CREATE TABLE `TB_TERM_CTGRY` (
  `TERM_CTGRY_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `REG_DT` datetime DEFAULT NULL,
  `REG_IP` varchar(15) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `DISPLAY_METHOD` varchar(15) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CHG_DT` datetime DEFAULT NULL,
  `CHG_IP` varchar(15) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `REQUIRED_YN` tinyint(1) DEFAULT NULL,
  `STATUS` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `TERM_CTGRY_ORDER` int(11) DEFAULT NULL,
  `TITLE` varchar(300) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `USER_REQUIRED_YN` tinyint(1) DEFAULT NULL,
  `REG_ID` bigint(20) DEFAULT NULL,
  `CHG_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`TERM_CTGRY_ID`),
  KEY `REG_ID` (`REG_ID`),
  KEY `CHG_ID` (`CHG_ID`),
  CONSTRAINT `tb_term_ctgry_ibfk_1` FOREIGN KEY (`REG_ID`) REFERENCES `TB_USER` (`USER_ID`),
  CONSTRAINT `tb_term_ctgry_ibfk_2` FOREIGN KEY (`CHG_ID`) REFERENCES `TB_USER` (`USER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- base_node_test.TB_BOARD definition

CREATE TABLE `TB_BOARD` (
  `BOARD_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `APPROVE_DATE` datetime DEFAULT NULL,
  `APPROVE_STATUS` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CANCEL_DATE` datetime DEFAULT NULL,
  `COMMENT_CNT` bigint(20) DEFAULT NULL,
  `CONTENT` longtext COLLATE utf8mb4_unicode_ci,
  `REG_DT` datetime DEFAULT NULL,
  `REG_IP` varchar(15) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `BOARD_FILE_IDS` varchar(1000) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `LIKE_CNT` bigint(20) DEFAULT NULL,
  `MENU_UID` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CHG_DT` datetime DEFAULT NULL,
  `CHG_IP` varchar(15) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `REJECT_DATE` datetime DEFAULT NULL,
  `BOARD_REPRESENT_IMG` varchar(300) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `SLUG` varchar(300) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `STATUS` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `BOARD_TAG` varchar(3000) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `TITLE` varchar(300) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `TOP_YN` tinyint(1) DEFAULT NULL,
  `VIEW_CNT` bigint(20) DEFAULT NULL,
  `REG_ID` bigint(20) DEFAULT NULL,
  `CATE_ID` bigint(20) DEFAULT NULL,
  `CHG_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`BOARD_ID`),
  KEY `IDX_BOARD__TITLE` (`TITLE`),
  KEY `IDX_BOARD__SLUG` (`SLUG`),
  KEY `IDX_BOARD__MENU_UID` (`MENU_UID`),
  KEY `REG_ID` (`REG_ID`),
  KEY `CATE_ID` (`CATE_ID`),
  KEY `CHG_ID` (`CHG_ID`),
  CONSTRAINT `tb_board_ibfk_3` FOREIGN KEY (`REG_ID`) REFERENCES `TB_USER` (`USER_ID`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `tb_board_ibfk_4` FOREIGN KEY (`CATE_ID`) REFERENCES `TB_BOARD_CTGRY` (`BOARD_CTGRY_ID`),
  CONSTRAINT `tb_board_ibfk_5` FOREIGN KEY (`CHG_ID`) REFERENCES `TB_USER` (`USER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=181 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- base_node_test.TB_BOARD_LIKE definition

CREATE TABLE `TB_BOARD_LIKE` (
  `BOARD_ID` bigint(20) NOT NULL,
  `USER_ID` bigint(20) NOT NULL,
  `REG_DT` datetime DEFAULT NULL,
  `REG_IP` varchar(15) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`BOARD_ID`,`USER_ID`),
  KEY `FK_BOARDLIKE_TO_USER` (`USER_ID`),
  CONSTRAINT `FK_BOARDLIKE_TO_BOARD` FOREIGN KEY (`BOARD_ID`) REFERENCES `TB_BOARD` (`BOARD_ID`),
  CONSTRAINT `FK_BOARDLIKE_TO_USER` FOREIGN KEY (`USER_ID`) REFERENCES `TB_USER` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- base_node_test.TB_TERM definition

CREATE TABLE `TB_TERM` (
  `TERM_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CONTENT` longtext COLLATE utf8mb4_unicode_ci,
  `REG_DT` datetime DEFAULT NULL,
  `REG_IP` varchar(15) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CHG_DT` datetime DEFAULT NULL,
  `CHG_IP` varchar(15) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `NOW_YN` tinyint(1) DEFAULT NULL,
  `PUBLISH_DT` datetime DEFAULT NULL,
  `STATUS` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `REG_ID` bigint(20) DEFAULT NULL,
  `CHG_ID` bigint(20) DEFAULT NULL,
  `TERM_CTGRY_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`TERM_ID`),
  KEY `IDX_TERM__PUBLISH_DT` (`PUBLISH_DT`),
  KEY `IDX_TERM__STATUS` (`STATUS`),
  KEY `REG_ID` (`REG_ID`),
  KEY `CHG_ID` (`CHG_ID`),
  KEY `TERM_CTGRY_ID` (`TERM_CTGRY_ID`),
  CONSTRAINT `tb_term_ibfk_4` FOREIGN KEY (`REG_ID`) REFERENCES `TB_USER` (`USER_ID`),
  CONSTRAINT `tb_term_ibfk_5` FOREIGN KEY (`CHG_ID`) REFERENCES `TB_USER` (`USER_ID`),
  CONSTRAINT `tb_term_ibfk_6` FOREIGN KEY (`TERM_CTGRY_ID`) REFERENCES `TB_TERM_CTGRY` (`TERM_CTGRY_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- base_node_test.TB_TERM_AGREE definition

CREATE TABLE `TB_TERM_AGREE` (
  `TERM_ID` bigint(20) NOT NULL,
  `USER_ID` bigint(20) NOT NULL,
  `AGREE` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `REG_DT` datetime DEFAULT NULL,
  `REG_IP` varchar(15) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CHG_DT` datetime DEFAULT NULL,
  `CHG_IP` varchar(15) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `REG_ID` bigint(20) DEFAULT NULL,
  `CHG_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`TERM_ID`,`USER_ID`),
  KEY `FK_TERM_AGREE_TO_USER1` (`USER_ID`),
  KEY `REG_ID` (`REG_ID`),
  KEY `CHG_ID` (`CHG_ID`),
  CONSTRAINT `FK_TERM_AGREE_TO_TERM` FOREIGN KEY (`TERM_ID`) REFERENCES `TB_TERM` (`TERM_ID`),
  CONSTRAINT `tb_term_agree_ibfk_1` FOREIGN KEY (`REG_ID`) REFERENCES `TB_USER` (`USER_ID`),
  CONSTRAINT `tb_term_agree_ibfk_2` FOREIGN KEY (`CHG_ID`) REFERENCES `TB_USER` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- base_node_test.TB_TERM_AGREE_HISTORY definition

CREATE TABLE `TB_TERM_AGREE_HISTORY` (
  `TERM_AGREE_HISTORY_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `AGREE` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `REG_DT` datetime DEFAULT NULL,
  `REG_IP` varchar(15) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `TERM_ID` bigint(20) DEFAULT NULL,
  `USER_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`TERM_AGREE_HISTORY_ID`),
  KEY `TERM_ID` (`TERM_ID`),
  KEY `USER_ID` (`USER_ID`),
  CONSTRAINT `tb_term_agree_history_ibfk_3` FOREIGN KEY (`TERM_ID`) REFERENCES `TB_TERM` (`TERM_ID`),
  CONSTRAINT `tb_term_agree_history_ibfk_4` FOREIGN KEY (`USER_ID`) REFERENCES `TB_USER` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
